[tool.poetry]
name = "pyhydrophone"
version = "0.1.5"
description = "python package to read and calibrate hydrophone data"
authors = ["Clea Parcerisas <clea.parcerisas@vliz.be>"]
license = "OSI Approved :: MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "2.0.2"
requests = "^2.31.0"
scipy = "1.9.3"
soundfile = "0.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
